# Generated by Django 5.2.3 on 2025-07-11 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_price_course_price_per_hour_lesson_homework_and_more'),
        ('students', '0001_initial'),
        ('tutors', '0002_rename_languages_tutor_languages_spoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses_list',
            field=models.ManyToManyField(related_name='students_list', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='favorite_tutors',
            field=models.ManyToManyField(related_name='favorite_students', to='tutors.tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_homework_completed',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
