# Generated by Django 5.2.3 on 2025-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_enrolled_courses_student_courses_list_and_more'),
        ('tutors', '0002_rename_languages_tutor_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favorite_tutors',
            field=models.ManyToManyField(related_name='favorite_students_students', to='tutors.tutor'),
        ),
    ]
