# Generated by Django 5.2.3 on 2025-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_favorite_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_homework_completed',
            field=models.JSONField(default=list),
        ),
    ]
