# Generated by Django 5.2.5 on 2025-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_student_homework_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='favorite_tutors',
            new_name='favourite_tutors',
        ),
        migrations.AddField(
            model_name='student',
            name='messages_received',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
