# Generated by Django 5.2.5 on 2025-08-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_favorite_tutors_student_favourite_tutors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='messages_received',
        ),
    ]
