# Generated by Django 5.2.5 on 2025-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_messages_received'),
        ('tutors', '0004_tutorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='messages_received',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='favourite_tutors',
            field=models.ManyToManyField(blank=True, related_name='favorite_students_students', to='tutors.tutor'),
        ),
    ]
