# Generated by Django 5.2.5 on 2025-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_messages_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='messages_sent',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reviews',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_homework_sent',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
