# Generated by Django 5.2.5 on 2025-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Easy', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog_pictures/')),
                ('related_links', models.URLField(blank=True, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
