# Generated by Django 5.2.3 on 2025-07-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_review_tutor_alter_course_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='courseId',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(default='Default course detail'),
        ),
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.CharField(default='80', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.TextField(default='Default course mat'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_per_dollar',
            field=models.DecimalField(decimal_places=2, default='12', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price_per_toman',
            field=models.DecimalField(decimal_places=2, default='960', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='Default course req'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='Default course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=10),
        ),
    ]
