# Generated by Django 5.2.3 on 2025-07-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_active_students_course_courseid_course_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='language_flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(default='cr1001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='length',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_dollar',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_toman',
            field=models.DecimalField(decimal_places=2, default=960, max_digits=10),
        ),
    ]
