"""
Django settings for learnenglish project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 100
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 10

# CSRF is not used with JWT header auth, but keep this to silence strict checks:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost", "http://localhost:3000",
    "http://127.0.0.1", "http://127.0.0.1:3000",
    "http://localhost:5173", "http://127.0.0.1:5173",
    "http://fluentdoor.com", "https://fluentdoor.com",
    "http://www.fluentdoor.com", "https://www.fluentdoor.com",
]


SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # don’t send COOP from Django
# Don’t set COEP in Django at all


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_simplejwt',
     'corsheaders',
    'django_extensions',
    'drf_spectacular',
    'django_filters',
    'accounts',
    'courses',
    'students',
    'tutors',
    'blog'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.auth.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',  # Capture DEBUG level logs
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Capture logs from Django framework
            'propagate': True,
        },
        'tutors': {  # You can add this to capture logs specific to your app
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # add directly after SecurityMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]



# FRONTEND_URL = 'https://fluentdoor.com/'

ROOT_URLCONF = 'learnenglish.urls'

AUTH_USER_MODEL = 'accounts.User'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'learnenglish',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         #'HOST': '103.75.196.105',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'learnenglish.wsgi.application'



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Access token will expire after 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token will expire after 7 days (this can be adjusted as needed)
    'ROTATE_REFRESH_TOKENS': False,  # Keep the refresh token the same after each refresh request
    'BLACKLIST_AFTER_ROTATION': False,  # If set to True, it will blacklist the old refresh token after using it
    'UPDATE_LAST_LOGIN': True,  # Update the last login time in the user model
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


SPECTACULAR_SETTINGS = {
    "TITLE": "LearnEnglish API",
    "DESCRIPTION": "OpenAPI schema for LearnEnglish",
    "VERSION": "1.0.0",
    # If needed, temporarily relax/disable deep operations while debugging:
    # "COMPONENT_SPLIT_REQUEST": True,
    # "POSTPROCESSING_HOOKS": [],
    # You can also exclude problematic endpoints while you debug:
    # "EXCLUDE_PATHS": [r"^/some/broken/path/"],
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# optional (nice to have)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Google OAuth Configuration
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# For development
GOOGLE_REDIRECT_URI = os.environ.get('GOOGLE_REDIRECT_URI', 'http://localhost:8000/auth/google/callback/')

# Frontend URL for redirects after OAuth
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')


GOOGLE_OAUTH_SCOPES = [
    'openid',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]



# Cookie settings for JWT
# JWT_COOKIE_DOMAIN = None  # For localhost development
# JWT_COOKIE_SECURE = False  # True in production with HTTPS
# JWT_COOKIE_HTTPONLY = True
# JWT_COOKIE_SAMESITE = 'Lax'  # 'Lax' or 'Strict' for CSRF protection
