# Generated by Django 5.2.3 on 2025-08-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_rename_languages_tutor_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tutor',
            name='intro_video_file',
            field=models.FileField(blank=True, null=True, upload_to='tutor_videos/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='intro_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TutorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tutors.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=120)),
                ('institution_name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('field', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='tutors.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='tutors.tutor')),
            ],
        ),
    ]
