# Generated by Django 5.2.5 on 2025-08-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutor_bio_tutor_country_tutor_intro_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField()),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson_package', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('days_available', models.JSONField(blank=True, default=list)),
                ('time_slots', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutors.tutor')),
            ],
        ),
    ]
