# Generated by Django 5.2.5 on 2025-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='expectation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='teaching_style',
            field=models.TextField(blank=True, default=''),
        ),
    ]
