# Generated by Django 5.2.5 on 2025-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutor_expectation_tutor_teaching_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
